# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sketches.Tag'),
        ),
    ]
