# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_auto_20170420_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
