# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0003_sketch_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots'),
        ),
    ]
